### ISSUE TITLE
documentation examples

### ISSUE THREAD

**Issue by iulusoy** [statphysandml/MCMCSimulationLib#1]
in [doc/getting_started.md](./doc/getting_started.md): The Ising example is probably missing a config file, and also the `project_config.sh` file is not in `MCMCSimulationLib/bash_scripts/` - probably since it is ignored in your `.gitignore`.

## Build your own project
Navigate to `MCMCSimulationLib/bash_scripts/` and copy the `project_config.sh` file

`cp project_config_template.sh project_config.sh`
You can leave the defined parameters for the moment. More details on the meaning of the parameters is explained in the README.md file.

Next, build a new (template) project by running:

`bash build_project.sh`

**Comment by iulusoy** [comment]
I think the issue is that you got multiple folders with bash scripts, I had navigated to examples but actually the necessary folder is in the main directory.

**Comment by lukaskades** [comment]
Hey iulusoy, thanks for the comment! I rearranged the project so that config files are no longer necessary.
